### PR TITLE
Add kicad files to release directories

### LINKED ISSUE #25: Copy the kicad versions from the tags into the releases directory
And probably update the [`release.sh`](https://github.com/im-tomu/tomu-hardware/blob/master/release.sh) script too.

Makes it easy for people to open older versions.

### PR DESCRIPTION
**Pull request by kitlith**
While I was at it, I added a folder for v0.0. I didn't do this for v0.4 because there is no tag for it.

Since v0.3 is missing a tag, I did not add the kicad file to that yet. (psst: if a tag is added then I'll add that to this PR. :P)

For the future, release.sh now copies the kicad file over to the output directory.

EDIT: Right, would fix #25

### CODE REVIEW

**Comment by xobs** [comment]
Thanks for this!  I've added a tag for v0.3.

**Comment by kitlith** [comment]
Alright, copied the kicad file into the v0.3 release and did a `rebase -i` to merge it with the existing commit for that.

Did I put everything in the right place?

**Comment by xobs** [comment]
That looks very good.  Thank you for the patchset!

**Comment by kitlith** [comment]
You're welcome!

**Pull request merged**
