### PR TITLE
Make compatible with kitspace.org

### PR DESCRIPTION
**Pull request by kasbah**
Hey, I sorted out the BOM and added the little bits required for adding it to [kitspace.org](https://kitspace.org).

I am assuming `EFM32HG309F64G-B-QFN24` is compatible with `EFM32HG309F64G-A-QFN24` as the later has gone EOL (but `B` is not yet stocked everywhere). The BOM seems pretty good for Digi-Key (your initial BOM),  Mouser and Farnell. In the other places it still has some pretty high MOQ items but I think it's hard to avoid. It's worth checking the BOM (you can load it and add to carts using [1-click BOM](https://1clickbom.com)) to see if I have selected anything stupid. 

[Here is a preview of the Kitspace page](http://add-tomu.preview.kitnic.it/boards/github.com/kitspace-forks/tomu-hardware/). Let me know if you see any issues or are happy to add it.

### CODE REVIEW

**Comment by mithro** [comment]
LGTM!

**Comment by kasbah** [comment]
It's up: https://kitspace.org/boards/github.com/im-tomu/tomu-hardware/

**Comment by mithro** [comment]
Awesome work!

Does kitscape also do the PCB ordering side of things?

**Comment by kasbah** [comment]
Not really, you download the gerbers and order yourself. I _will_ be adding direct links to some batching services soon and at some point we will hopefully have price estimates on the page as well.

**Comment by mithro** [comment]
@kasbah - OHS Park is a pretty good option for the Tomu due to the ability to not end up with like 100 boards :-P

Drew (https://github.com/pdp7 @pdp7) just built his own Tomu board and might be interested in helping with OHS Park integration?

**Pull request merged**
