### PR TITLE
5x5 and 10x10 cm panels for DirtyPCB service

### PR DESCRIPTION
**Pull request by zigastegu**
5x5 panel:     120pcs for 16$
10x10 panel: 420pcs for 25$

Using GerberTools from ThisIsNotRocketScience

HOW:
KiCad:
- Defined auxiliary axis in one corner of the board for easier positioning
- Export Gerbers with Use auxiliary axis as origin = TRUE

In Panelizer:
- rename outline from .GM1 to .GKO
- import Gerbers folder
- add multiple instances

### CODE REVIEW

**Comment by mithro** [comment]
Hi @luftek,

I would actually love to merge this CL and it was bad for me to let it drop!

Did you ever end up ordering these from DirtyPCB at all? If not, can you send me your address and I'll order some to be delivered to you so can review if the panelization looks okay.

**Comment by zigastegu** [comment]
Will panelize latest version of Gerbers if you need, still. I don't know your quantities

**Comment by mithro** [comment]
I think everything you did in your first pull request was correct. We were just waiting to actually make some of the panels on DirtyPCB to verify everything was okay.

As far as I know, the version you panelized is still the current "released" version so would be the right one to panelize.

**Comment by zigastegu** [comment]
Will do this on 7th Avg and delete this comment then

**Comment by mithro** [comment]
@luaks Hrm? 7th July was in the past - I assume you mean 7th August?

As mentioned, once you have uploaded the Gerbers files, send me an address (mithro@mithis.com) and I'll get a DirtyPCB order sent to you using them.

**Pull request closed without merging**
