### PR TITLE
pcb: add features for orienting a case

### PR DESCRIPTION
**Pull request by xobs**
Add some round features on the sides to allow for lining up the PCB with
an external case.

### CODE REVIEW

**Comment by mithro** [comment]
Could you attach a quick picture of the diff?

**Comment by xobs** [comment]
before-after

**Comment by xobs** [comment]
The resolution of plastic features is about 1mm, so the divots are slightly bigger at 1.1mm each.  The plan is to create a shell that slots into these divots, possibly gluing it on top if necessary.

**Comment by mithro** [comment]
Is this ready to merge?

**Comment by xobs** [comment]
Yes it is.

**Pull request merged**
